#include <cardinal.h>

ULONG_PTR cardinal_base;
ULONG_PTR cardinal_pg_sz;
PKBUGCHECK_REASON_CALLBACK_RECORD callback_record;

VOID cardinal_get_info() {

    /*
        Get the base address and size of the anti-cheat driver,
        based off the size calculate how many pages we need
        to remove from the crash dump.
    */

    ULONG_PTR base = 0;
    ULONG_PTR size = 0;
    UNICODE_STRING drv_name;
    UNICODE_STRING module_list;
    RtlInitUnicodeString(&drv_name, L"cardinal.sys");
    RtlInitUnicodeString(&module_list, L"PsLoadedModuleList");

    PLIST_ENTRY PsLoadedModuleList = MmGetSystemRoutineAddress(&module_list);
    if (!PsLoadedModuleList)
        return;

    PKLDR_DATA_TABLE_ENTRY entry = (PKLDR_DATA_TABLE_ENTRY)PsLoadedModuleList->Flink;
    while ( (PLIST_ENTRY)entry != PsLoadedModuleList ) {

        if ( !RtlCompareUnicodeString(&entry->BaseDllName, &drv_name, TRUE) ) {
            base = (ULONG_PTR)entry->DllBase;
            size = (ULONG_PTR)entry->SizeOfImage;
            break;
        }
        
        entry = (PKLDR_DATA_TABLE_ENTRY)entry->InLoadOrderLinks.Flink;
    }

    // Calculate how many pages to remove, accounting for an extra page.
    cardinal_pg_sz = (size + PAGE_SIZE - 1) / PAGE_SIZE;
    cardinal_base = base;

}

VOID cardinal_bugcheck_cb(KBUGCHECK_CALLBACK_REASON Reason, PKBUGCHECK_REASON_CALLBACK_RECORD Record, PVOID ReasonSpecificData, ULONG ReasonSpecificDataLength) {
    PKBUGCHECK_REMOVE_PAGES bugcheck = (PKBUGCHECK_REMOVE_PAGES)ReasonSpecificData;
    if ( // Bug checks intentionally generated by the keyboard and NotMyFault
        bugcheck->BugCheckCode == MANUALLY_INITIATED_CRASH ||
        bugcheck->BugCheckCode == KERNEL_MODE_HEAP_CORRUPTION ||
        bugcheck->BugCheckCode == PAGE_FAULT_IN_NONPAGED_AREA ||
        bugcheck->BugCheckCode == DRIVER_OVERRAN_STACK_BUFFER ||
        bugcheck->BugCheckCode == DRIVER_IRQL_NOT_LESS_OR_EQUAL
    ) {
        bugcheck->Flags |= KB_REMOVE_PAGES_FLAG_VIRTUAL_ADDRESS;
        bugcheck->Address = cardinal_base;  // The base address of this anti-cheat driver.
        bugcheck->Count = cardinal_pg_sz;   // How many pages from the start of our driver to remove from the dump.
    }
}

VOID cardinal_dmp_hide() {

    /*
        Register the bug check reason callback
    */
    
    callback_record = ExAllocatePoolWithTag(NonPagedPool, sizeof(KBUGCHECK_REASON_CALLBACK_RECORD), CARDINAL_MEM_TAG);
    if (!callback_record)
        return;

    cardinal_get_info();
    UCHAR component[] = "Bugcheckin\n";
    KeInitializeCallbackRecord(callback_record);
    KeRegisterBugCheckReasonCallback(callback_record, cardinal_bugcheck_cb, KbCallbackRemovePages, component);
    
}

VOID cardinal_unload(PDRIVER_OBJECT DriverObject) {
    DbgPrint("[CARD] Unloading..\n");
    KeDeregisterBugCheckReasonCallback(callback_record);
    ExFreePoolWithTag(callback_record, CARDINAL_MEM_TAG);
}

NTSTATUS cardinal_entry(PDRIVER_OBJECT DriverObject, PUNICODE_STRING RegistryPath) {

    DbgPrint("[CARD] Loading..\n");
    DriverObject->DriverUnload = cardinal_unload;
    cardinal_dmp_hide();

    return STATUS_SUCCESS;
}